// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loggerSchema.proto

package comm.grpc.logger.stub;

public interface LogDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string appName = 1;</code>
   */
  java.lang.String getAppName();
  /**
   * <code>string appName = 1;</code>
   */
  com.google.protobuf.ByteString
      getAppNameBytes();

  /**
   * <code>string className = 2;</code>
   */
  java.lang.String getClassName();
  /**
   * <code>string className = 2;</code>
   */
  com.google.protobuf.ByteString
      getClassNameBytes();

  /**
   * <code>string methodName = 3;</code>
   */
  java.lang.String getMethodName();
  /**
   * <code>string methodName = 3;</code>
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>string type = 4;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string requestLogMessage = 5;</code>
   */
  java.lang.String getRequestLogMessage();
  /**
   * <code>string requestLogMessage = 5;</code>
   */
  com.google.protobuf.ByteString
      getRequestLogMessageBytes();

  /**
   * <code>string responseLogMessage = 6;</code>
   */
  java.lang.String getResponseLogMessage();
  /**
   * <code>string responseLogMessage = 6;</code>
   */
  com.google.protobuf.ByteString
      getResponseLogMessageBytes();

  /**
   * <code>string logTime = 7;</code>
   */
  java.lang.String getLogTime();
  /**
   * <code>string logTime = 7;</code>
   */
  com.google.protobuf.ByteString
      getLogTimeBytes();
}
