// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loggerSchema.proto

package comm.grpc.logger.stub;

public interface LogMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LogMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string logMessage = 2;</code>
   */
  java.lang.String getLogMessage();
  /**
   * <code>string logMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getLogMessageBytes();

  /**
   * <code>string logTime = 3;</code>
   */
  java.lang.String getLogTime();
  /**
   * <code>string logTime = 3;</code>
   */
  com.google.protobuf.ByteString
      getLogTimeBytes();
}
